### ISSUE TITLE
App always requests a default-url-handler-scheme change

### ISSUE THREAD

**Issue by ludvigng** [ytmdesktop/ytmdesktop#630]
- [ x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x ] I verified that there is no open issue for the same subject.

**Describe the bug**
Opening the app, I get a window asking me if I want to allow a settings change, see screenshot for details. Whether i click yes or no, it reappears on the next launch.

**To Reproduce**
Starting the app in any way shows the question.

**Expected behavior**
Setting it once should suffice. Checking xdg-settings from my regular shell shows this:
`❯ xdg-settings get default-url-scheme-handler ytmd`
`youtube-music-desktop-app_youtube-music-desktop-app.desktop`

Meanwhile the same command in the snap with **snap --shell youtube-music-desktop-app** shows this:
`$ xdg-settings get default-url-scheme-handler ytmd`
`youtube-music-desktop-app.desktop`

Trying to change the value inside the snap results in an error:
`Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" subproperty "ytmd" setting to invalid value "youtube-music-desktop-app_youtube-music-desktop-app.desktop"`

**Screenshots**
![Skärmbild från 2021-02-19 20-39-30](https://user-images.githubusercontent.com/50339757/108555650-09fc8f00-72f6-11eb-9c6f-d0e784adf45b.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0***
 * OS: ***Linux***
 * OS version: ***Ubuntu 20.10***
 * Arch: ***x64***
* Installation way: ***snapcraft***

**Comment by fortizc** [comment]
Hi, same problem here running on Ubuntu 20.04

**Comment by ludvigng** [comment]
I changed OS and it's also happening when running manjaro linux 20.2.1 with the snap version.

**Comment by NovusTheory** [comment]
I'm unsure if this issue is specifically for snap but the PR above should fix this issue. There is no snap build to test though it seems.

**Comment by ChristianWilkie** [comment]
Same problem here in Ubuntu 20.10, using snap youtube-music-desktop-app v1.13.0

**Comment by fmmarzoa** [comment]
Just came here to add my "me too" comment. Ubuntu 20.04, youtube music 1.13.0 installed with snap.

**Comment by diegosilberg** [comment]
Also present on Debian bullseye

**Comment by akabakass** [comment]
maybe something like this could help:
https://github.com/snapcore/snapd/pull/4073

**Comment by ahmedatawfik** [comment]
Same here with Ubuntu 20.04, snap  youtube-music-desktop-app 1.13.0 from Adler (adlerluiz)

**Comment by leonp5** [comment]
Same with Linux Mint 20.2 (Ubuntu 20.04), snap ferdi app.
Does anybody know a workaround?

**Comment by ludvigng** [comment]
> snap ferdi app.

???

Well, a fix was merged almost 6 months ago so I'm going to close this, since it'll likely be fixed with the next release.

**Comment by Alipoodle** [comment]
This issue was left still open as once all the PRs are moved into Live/a release all the issues will be closed.
if you wish to close it then fine, but it's easier for people to find when open.

**Comment by ludvigng** [comment]
Alright, that's a fair point! I'll leave it open then :)

**Comment by sfllaw** [comment]
This is still broken on the latest 1.13.0 release on Ubuntu 22.04.

**Comment by emersonbarros** [comment]
After try to use ytmdesktop for many times I discovered the YTM via Chrome webapp works much better.

**Comment by julian-alarcon** [comment]
Yeap, I had the same feeling @emersonbarros . This Electron App takes a lot of memory and it's sometimes really slow.

**Comment by A-Matt** [comment]
![image](https://user-images.githubusercontent.com/47449129/168043907-ca509fa5-22e6-469a-b188-99f3f28713d3.png)

**Comment by immartian** [comment]
It's still there with Ubuntu 22.04LTS.

**Comment by arevalosoft** [comment]
In my case, I surpassed the issue by uninstalling the snap package and installing the application from the application store in Pop! OS.

![ytmdesktop-install](https://user-images.githubusercontent.com/11032850/178867967-966b9217-972a-498e-b84d-9015e6f6d72c.png)

**Comment by Alipoodle** [comment]
As shown in the Labels on this issue.
This has been fixed in the Development Builds.

Version Development versions **1.14.1** & **1.14.2** have this patch in, BUT not in the **1.13** Release.
So you can use those ones

**Comment by AxMx13** [comment]
It is still showing every time on Ubuntu 22.04, installed via snap

**Comment by log-borica** [comment]
Hello everyone, i just had the same issue using snap. If you're having the same behaviour with the dialog popping up everytime, i was able fix it by installing it direcly from the latest [release](https://github.com/ytmdesktop/ytmdesktop/releases), without snap using the `.deb` file. I am using Ubuntu 25.04.

**Comment by Alipoodle** [comment]
Fix with V2
